### ISSUE TITLE
Update for 5.0

### ISSUE THREAD

**Issue by iwantcookiesnow** [QiqisFather/universal_roll_simulator#1]
Hello, could you please update the simulator for the 5.0 changes? The changes are: 

- the character banner is slightly more in our favor and has a 55/45 chance now
- the weapon banner needs one fate point less (2nd 5* is guaranteed) to get the selected weapon

It'd be great to have those changes because I frequently use your simulator. Thanks!

**Comment by QiqisFather** [comment]
Hello! Thanks for the heads-up. I updated the internal logic to reflect the new changes. 
Cheers,
